Repository TP1-Competition/MilRoute, pull requests merged in 2023-07, with the labels that each got.

#82 [feat] 79 경로 테이블 설계
  back/src/main/java/com/tp1/back/member/domain/Member.java
  back/src/main/java/com/tp1/back/path/domain/BusPath.java
  back/src/main/java/com/tp1/back/path/domain/Path.java
  back/src/main/java/com/tp1/back/path/domain/PathType.java
  back/src/main/java/com/tp1/back/path/domain/SubwayPath.java
  back/src/main/java/com/tp1/back/path/domain/WalkPath.java
  back/src/main/java/com/tp1/back/place/domain/Place.java
  back/src/main/java/com/tp1/back/route/domain/Route.java
  back/src/main/java/com/tp1/back/routeplace/domain/RoutePlace.java
  back/src/main/resources/db/prod/schema.sql
Labels: Feature, BE

#84 [feat] 41 최적 경로 계산 기능을 개발한다
  back/src/main/java/com/tp1/back/auth/application/JwtService.java
  back/src/main/java/com/tp1/back/path/application/ODsayPathProvider.java
  back/src/main/java/com/tp1/back/path/application/PathProvider.java
  back/src/main/java/com/tp1/back/path/application/PathService.java
  back/src/main/java/com/tp1/back/path/domain/BusPath.java
  back/src/main/java/com/tp1/back/path/domain/Path.java
  back/src/main/java/com/tp1/back/path/domain/PathRepository.java
  back/src/main/java/com/tp1/back/path/domain/PathType.java
  back/src/main/java/com/tp1/back/path/domain/SubPath.java
  back/src/main/java/com/tp1/back/path/domain/SubPathRepository.java
  back/src/main/java/com/tp1/back/path/domain/SubwayPath.java
  back/src/main/java/com/tp1/back/path/domain/WalkPath.java
  back/src/main/java/com/tp1/back/path/dto/ODsayResponse.java
  back/src/main/java/com/tp1/back/path/dto/PathDto.java
  back/src/main/java/com/tp1/back/path/dto/SubPathDto.java
  back/src/main/java/com/tp1/back/place/application/PlaceMapper.java
  back/src/main/java/com/tp1/back/place/application/PlaceService.java
  back/src/main/java/com/tp1/back/place/domain/Place.java
  back/src/main/java/com/tp1/back/place/domain/PlaceRepository.java
  back/src/main/java/com/tp1/back/place/dto/PlaceDto.java
  back/src/main/java/com/tp1/back/route/application/OptimalRouteService.java
  back/src/main/java/com/tp1/back/route/domain/Route.java
  back/src/main/java/com/tp1/back/route/domain/RouteRepository.java
  back/src/main/java/com/tp1/back/route/dto/OptimalPathDto.java
  back/src/main/java/com/tp1/back/route/dto/OptimalRoutePlaceDto.java
  back/src/main/java/com/tp1/back/route/dto/OptimalRouteRequest.java
  back/src/main/java/com/tp1/back/route/dto/OptimalRouteResponse.java
  back/src/main/java/com/tp1/back/route/dto/OptimalSubPathDto.java
  back/src/main/java/com/tp1/back/route/presentation/RouteController.java
  back/src/main/java/com/tp1/back/routeplace/domain/RoutePlace.java
  back/src/main/java/com/tp1/back/routeplace/domain/RoutePlaceRepository.java
  back/src/main/resources/application-prod.yml
  back/src/main/resources/application.yml
  back/src/main/resources/db/prod/schema.sql
  back/src/test/java/com/tp1/back/path/domain/PathTest.java
Labels: Api, BE

#85 [feat] 42 저장된 최적 경로 관리 기능을 개발한다
  back/src/main/java/com/tp1/back/member/application/MemberService.java
  back/src/main/java/com/tp1/back/member/application/RegisterRouteService.java
  back/src/main/java/com/tp1/back/member/dto/RegisterRouteRequest.java
  back/src/main/java/com/tp1/back/member/dto/RouteDto.java
  back/src/main/java/com/tp1/back/member/dto/RoutesResponse.java
  back/src/main/java/com/tp1/back/member/presentation/MemberController.java
  back/src/main/java/com/tp1/back/member/presentation/RegisterRouteController.java
  back/src/main/java/com/tp1/back/path/application/PathService.java
  back/src/main/java/com/tp1/back/path/domain/Path.java
  back/src/main/java/com/tp1/back/route/application/OptimalRouteService.java
  back/src/main/java/com/tp1/back/route/domain/Route.java
  back/src/main/java/com/tp1/back/route/dto/OptimalRouteResponse.java
  back/src/main/java/com/tp1/back/route/presentation/RouteController.java
  back/src/main/resources/db/prod/schema.sql
Labels: Api, BE

#87 design/server구축/#86
  front/.dockerignore
  front/Dockerfile.dev
  front/docker-compose.yml
  front/package.json
  front/public/Img/Biglogo.png
  front/public/Img/mainlogo.png
  front/public/Img/milroutelogo.png
  front/public/Img/milsale.png
  front/public/Img/mobilemilsale.png
  front/public/Img/outline.png
  front/public/index.html
  front/src/Layout.js
  front/src/component/FooterBar/FooterBar.js
  front/src/component/FooterBar/style.js
  front/src/component/NaverMap/NaverMap.js
  front/src/component/Outlayout/Outlayout.js
  front/src/index.css
  front/src/index.js
  front/src/page/AreaChoice/AreaChoice.js
  front/src/page/AreaChoice/style.js
  front/src/page/BookMark/BookMark.js
  front/src/page/BookMark/style.js
  front/src/page/LastDesti/LastDesti.js
  front/src/page/LastDesti/style.js
  front/src/page/MainPage/MainPage.js
  front/src/page/MainPage/style.js
  front/src/page/SelectDesti/SelectDesti.js
  front/src/page/SelectDesti/style.js
  front/src/page/SignUp/SignUp.js
  front/src/page/StartDesti/StartDesti.js
  front/src/page/StartDesti/style.js
  front/src/routes/IsRouter.js
  nodeserver/.gitignore
  nodeserver/package.json
  nodeserver/server.js
  nodeserver/yarn.lock
Labels: Api, Design, format, remove, Setting, FE

#88 [feat] 사용자는 최단 경로를 볼 수 있다
  front/public/Img/marker.png
  front/public/index.html
  front/src/component/Input/CheckBox.js
  front/src/component/Input/style.js
  front/src/component/MapInfo/BusRoute.js
  front/src/component/MapInfo/CarRoute.js
  front/src/component/MapInfo/PlaceOrder.js
  front/src/component/MapInfo/RouteInfo.js
  front/src/component/MapInfo/StationInfo.js
  front/src/component/MapInfo/style.js
  front/src/page/ShortRoute/Info/CarInfo.js
  front/src/page/ShortRoute/Info/PublicInfo.js
  front/src/page/ShortRoute/Map/KaKaoMapCar.js
  front/src/page/ShortRoute/Map/KakaoMapPublic.js
  front/src/page/ShortRoute/Map/a.json
  front/src/page/ShortRoute/ShortRoute.js
  front/src/page/ShortRoute/api/busApi.js
  front/src/page/ShortRoute/api/carApi.js
  front/src/page/ShortRoute/style.js
  front/src/page/SignIn/SignIn.js
  front/src/page/SignIn/SignInForm.js
  front/src/page/SignIn/style.js
  front/src/page/SignUp/Agreement/AgreementPage.js
  front/src/page/SignUp/Agreement/AgreemetTextContainer.js
  front/src/page/SignUp/Agreement/agreementText.js
  front/src/page/SignUp/Agreement/style.js
  front/src/page/SignUp/SignUp.js
  front/src/page/SignUp/style.js
  front/src/routes/IsRouter.js
Labels: Design, Feature, FE

#91 FE/데이터전달/#90
  front/src/page/LastDesti/LastDesti.js
  front/src/page/MainPage/MainPage.js
Labels: FE

#92 [style] 89 이용약관 동의 페이지 오류 수정
  front/src/component/Input/CheckBox.js
  front/src/page/ShortRoute/ShortRoute.js
  front/src/page/ShortRoute/api/busApi.js
  front/src/page/SignIn/SignIn.js
  front/src/page/SignIn/style.js
  front/src/page/SignUp/Agreement/AgreementPage.js
  front/src/page/SignUp/Agreement/style.js
  front/src/page/SignUp/SignUp.js
  front/src/page/SignUp/style.js
Labels: FE

#95 api/최적경루구하기api/#94
  front/src/page/LastDesti/LastDesti.js
  front/src/page/MainPage/MainPage.js
Labels: Api, FE

#96 [feat]93 최적경로를 출력하고 최적경로를 저장한다
  front/src/component/MapInfo/BusRoute.js
  front/src/page/ShortRoute/Map/KakaoMapPublic.js
  front/src/page/ShortRoute/ShortRoute.js
  front/src/page/ShortRoute/api/busApi.js
Labels: Api, FE

#98 api/즐겨찾기api연동/#97
  front/src/component/FooterBar/FooterBar.js
  front/src/context/LoginContext.js
  front/src/page/AreaChoice/AreaChoice.js
  front/src/page/BookMark/BookMark.js
  front/src/page/BookMark/style.js
  front/src/page/LastDesti/LastDesti.js
  front/src/page/MainPage/MainPage.js
  front/src/page/MainPage/style.js
  front/src/page/SelectDesti/SelectDesti.js
  nodeserver/server.js
Labels: Api, FE
