Repository TP1-Competition/MilRoute, pull requests merged in 2023-06, with the labels that each got.

#20 [design] 내 정보 관리 페이지를 마크업 및 스타일링을 한다.
  front/src/page/MyPage/ManageInfo.js
  front/src/page/MyPage/MyPage.js
  front/src/page/MyPage/style.js
  front/src/routes/IsRouter.js
Labels: Design

#27 [feat]18 회원가입 기능을 개발한다
  back/src/main/java/com/tp1/back/member/application/MemberService.java
  back/src/main/java/com/tp1/back/member/domain/Member.java
  back/src/main/java/com/tp1/back/member/domain/MemberRepository.java
  back/src/main/java/com/tp1/back/member/dto/RegisterRequest.java
  back/src/main/java/com/tp1/back/member/presentation/MemberController.java
  back/src/main/resources/db/prod/schema.sql
  back/src/test/java/com/tp1/back/common/fixtures/MemberFixtures.java
  back/src/test/java/com/tp1/back/member/application/MemberServiceTest.java
  back/src/test/java/com/tp1/back/member/domain/MemberRepositoryTest.java
  back/src/test/java/com/tp1/back/member/domain/MemberTest.java
  back/src/test/java/com/tp1/back/member/presentation/MemberControllerTest.java
Labels: Api, Feature

#26 feat: 로그인 기능 구현
  front/src/page/SignIn/SignInForm.js
  front/src/page/SignIn/style.js
Labels: Feature

#35 Design/34-회원은-장소를-검색하기-위해-지역을-선택하고-싶다/#34
  front/src/App.js
  front/src/page/AreaChoice/AreaChoice.js
  front/src/page/AreaChoice/style.js
  front/src/routes/IsRouter.js
Labels: Design

#37 setting/sweetAlert dotenv 설치 및 추가 커밋다시올리기/#36
  front/.gitignore
  front/package.json
  front/src/css/alert.css
  front/src/page/AreaChoice/AreaChoice.js
  front/src/page/AreaChoice/style.js
  front/src/page/MainPage/MainPage.js
  front/src/page/MainPage/style.js
  front/yarn.lock
Labels: Design, Setting

#53 [design] 약관동의 컴포넌트를 만든다
  front/src/page/SignUp/Agreement/AgreementPage.js
  front/src/page/SignUp/Agreement/style.js
  front/src/routes/IsRouter.js
Labels: Design

#59 design/theme.js 생성/#58
  front/src/App.js
  front/src/page/MainPage/MainPage.js
  front/src/routes/IsRouter.js
Labels: Design

#61 [feat] 48 테스트용 도커 파일 추가
  back/test.Dockerfile
Labels: Deploy

#55 feat: 회원 탈퇴 페이지 마크업 및 스타일링
  front/src/component/Input/CheckBox.js
  front/src/component/Input/style.js
  front/src/page/DeleteAccount/DeleteAccount.js
  front/src/page/DeleteAccount/style.js
  front/src/routes/IsRouter.js
Labels: Design, Feature

#69 format/footer수정/#64
  front/src/App.js
  front/src/Layout.js
  front/src/component/FooterBar/FooterBar.js
  front/src/routes/IsRouter.js
Labels: Design, format

#70 disign/여행지 선택 페이지 디자인 및 목업/#65
  front/public/index.html
  front/src/component/FooterBar/style.js
  front/src/component/NaverMap/NaverMap.js
  front/src/page/AreaChoice/AreaChoice.js
  front/src/page/MainPage/style.js
  front/src/page/SelectDesti/SelectDesti.js
  front/src/page/SelectDesti/style.js
  front/src/styles/theme.js
Labels: Design

#75 [feat] 사용자는 회원가입, 로그인을 할 수 있다.
  front/public/Img/CongratsPage/checkImg.svg
  front/src/App.js
  front/src/api/axiosConfig.js
  front/src/component/FooterBar/FooterBar.js
  front/src/context/LoginContext.js
  front/src/page/MainPage/MainPage.js
  front/src/page/SignIn/SignInForm.js
  front/src/page/SignUp/CongratsPage.js
  front/src/page/SignUp/SignUp.js
  front/src/page/SignUp/style.js
Labels: Api, Design, Feature, FE
